dist: bionic
language: node_js
services:
  - redis
  - mongodb
node_js:
  - "20.4"
cache:
  directories:
  - "node_modules"
env:
  global:
    - API_GATEWAY_EXTERNAL_URL=http://127.0.0.1:9000
    - CC_TEST_REPORTER_ID=5ce29b8570f7714ec7afd30a3ce89dedcff6af43d16dd0872e26237f2678b8a5
    - FASTLY_ENABLED=false
    - GATEWAY_URL=http://127.0.0.1:9000
    - HOST_IP=127.0.0.1
    - LOAD_CRON=false
    - MICROSERVICE_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    - NODE_ENV=test
    - PORT=8431
    - REDIS_URL=redis://localhost:6379
    - AWS_REGION=us-east-1
    - AWS_ACCESS_KEY_ID=test
    - AWS_SECRET_ACCESS_KEY=test

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test
  - yarn run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
