prod:
  image: vizzuality/gfw-subscription-api:1.0.6${STAGING}
  ports:
    - "3600"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  # log_driver: "gelf"
  restart: always
  links:
    - redis
  # log_opt:
  #   gelf-address: ${GELF_ADDRESS}
redis:
  image: redis
  container_name: gfw-subscriptions-api-redis
  ports:
    - "6379"
  restart: always
  environment:
      - reschedule=on-node-failure
