develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35725:35729"
  container_name: gfw-subscription-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_USER: wri-01
    FLAGSHIP_URL: http://staging.globalforestwatch.org
    API_GATEWAY_URL: http://192.168.1.169:9000
    API_URL: http://localhost:9000
    API_GATEWAY_EXTERNAL_URL: http://192.168.1.169:8000
    API_GATEWAY_QUEUE_URL: redis://192.168.1.169:6379
    API_GATEWAY_QUEUE_PROVIDER: redis
    API_GATEWAY_QUEUE_NAME: mail
    MIGRATE_URI: <migrateuri>
  command: develop
  links:
    - mongo
    - redis
  volumes:
    - ./app:/opt/gfw-subscription-api/app
redis:
  image: redis
  container_name: gfw-subscriptions-api-redis
  ports:
    - "6379"
  restart: always
mongo:
  image: mongo
  container_name: gfw-subscription-mongo
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - $HOME/docker/data/gfw-subscription-api:/data/db
  restart: always
