develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35725:35729"
  container_name: gfw-subscription-api-develop
  environment:
    NODE_ENV: dev
    FLAGSHIP_URL: http://staging.globalforestwatch.org
    API_GATEWAY_URL: http://192.168.99.100:8000
    API_GATEWAY_EXTERNAL_URL: http://192.168.99.100:8000
    API_GATEWAY_QUEUE_URL: redis://192.168.99.100:6379
    API_GATEWAY_QUEUE_PROVIDER: redis
    API_GATEWAY_QUEUE_NAME: mail
    MIGRATE_URI: <migrateuri>
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/gfw-subscription-api/app
mongo:
  image: mongo
  container_name: gfw-subscription-mongo
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - /var/docker/data/gfw-subscription-api:/data/db
  restart: always
