develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35725:35729"
  container_name: gfw-subscription-api-develop
  environment:
    NODE_ENV: dev
    API_GATEWAY_URI: http://192.168.99.100:8000
    API_GATEWAY_QUEUE_URL: redis://192.168.99.100:6379
    API_GATEWAY_QUEUE_PROVIDER: redis
    SELF_REGISTRY: "on"
    SPARKPOST_API_KEY: <apikey>
  command: develop
  volumes:
    - ./app:/opt/gfw-subscription-api/app
