version: "3"
services:
  develop:
    build: .
    ports:
      - "35725:35729"
    container_name: gfw-subscription-api-develop
    env_file:
      - dev.env
    environment:
      PORT: 35725
      NODE_PATH: app/src
      CT_REGISTER_MODE: auto
      NODE_ENV: dev
      CARTODB_USER: wri-01
      FLAGSHIP_URL: http://staging.globalforestwatch.org
      REDIS_URL: redis://redis:6379
      API_GATEWAY_QUEUE_PROVIDER: redis
      API_GATEWAY_QUEUE_NAME: mail
      REDIS_PORT_6379_TCP_ADDR: redis
      MONGO_PORT_27017_TCP_ADDR: mongo
      MONGO_PORT_27017_TCP_PORT: 27017
      API_VERSION: v1
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
    command: develop
    depends_on:
      - mongo
      - redis
    volumes:
      - ./app:/opt/gfw-subscription-api/app
  redis:
    image: redis
    container_name: gfw-subscriptions-api-redis
    ports:
      - "6379"
    restart: always

  mongo:
    image: mongo
    container_name: gfw-subscription-mongo
    ports:
      - "27021:27017"
    volumes:
      # in osx the host machine volume directory cannot be under /Users
      # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
      - $HOME/docker/data/gfw-subscription-api:/data/db
    restart: always
