prod:
  image: vizzuality/gfw-subscription-api:1.4.1${STAGING}
  ports:
    - "3600"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  links:
    - redis
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: gfw-subscription-api${STAGING}

redis:
  image: redis
  container_name: gfw-subscriptions-api-redis
  ports:
    - "6379"
  restart: always
  environment:
      - reschedule=on-node-failure
