apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: PORT
            value: "3600"
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://{name}.default.svc.cluster.local:3600
          - name: MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: SUBSCRIPTIONS_MONGO_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: STATS_RECIPIENTS
            value: sergio.gordillo@vizzuality.com,abarrett@wri.org,charlie.hofmann@wri.org,mweisse@wri.org,raul.requero@vizzuality.com
          - name: FLAGSHIP_URL
            value: http://staging.globalforestwatch.org
          - name: API_GATEWAY_EXTERNAL_URL
            value: http://staging-api.globalforestwatch.org
          - name: API_URL
            value: http://staging-api.globalforestwatch.org
          - name: CARTODB_USER
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CARTODB_USER
          - name: API_GATEWAY_QUEUE_PROVIDER
            value: redis
          - name: API_GATEWAY_QUEUE_NAME
            value: mail_prod
          - name: API_GATEWAY_QUEUE_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI

        ports:
          - containerPort: 3600

      restartPolicy: Always
