apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gfw
    name: subscriptions
  name: subscriptions
  namespace: gfw
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: subscriptions
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: subscriptions
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
        - args:
            - start
          env:
            - name: PORT
              value: "3600"
            - name: LOGGER_LEVEL
              value: info
            - name: NODE_ENV
              value: prod
            - name: MONGO_USE_UNIFIED_TOPOLOGY
              value: "false"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: SUBSCRIPTIONS_MONGO_URI
                  name: dbsecrets
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  key: GATEWAY_URL
                  name: mssecrets
            - name: MICROSERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  key: MICROSERVICE_TOKEN
                  name: mssecrets
            - name: FLAGSHIP_URL
              value: https://www.globalforestwatch.org
            - name: RW_FLAGSHIP_URL_PREPRODUCTION
              value: https://preproduction.resourcewatch.org
            - name: RW_FLAGSHIP_URL_PRODUCTION
              value: https://resourcewatch.org
            - name: RW_FLAGSHIP_URL_STAGING
              value: https://staging.resourcewatch.org
            - name: API_GATEWAY_EXTERNAL_URL
              value: https://api.resourcewatch.org
            - name: API_GATEWAY_QUEUE_NAME
              value: mail_prod
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: REDIS_URI
                  name: dbsecrets
            - name: REDIS_PORT_6379_TCP_PORT
              value: "6379"
            - name: SPARKPOST_KEY
              valueFrom:
                secretKeyRef:
                  key: SPARKPOST_KEY
                  name: mssecrets
            - name: SLACK_KEY
              valueFrom:
                secretKeyRef:
                  key: SLACK_KEY
                  name: mssecrets
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  key: SLACK_CHANNEL_ID
                  name: mssecrets
            - name: FASTLY_ENABLED
              valueFrom:
                secretKeyRef:
                  key: FASTLY_ENABLED
                  name: mssecrets
            - name: FASTLY_APIKEY
              valueFrom:
                secretKeyRef:
                  key: FASTLY_APIKEY
                  name: mssecrets
                  optional: true
            - name: FASTLY_SERVICEID
              valueFrom:
                secretKeyRef:
                  key: FASTLY_SERVICEID
                  name: mssecrets
                  optional: true
            - name: DATA_API_URL
              valueFrom:
                secretKeyRef:
                  key: DATA_API_URL
                  name: mssecrets
            - name: DATA_API_KEY
              valueFrom:
                secretKeyRef:
                  key: DATA_API_KEY
                  name: mssecrets
            - name: DATA_API_ORIGIN
              valueFrom:
                secretKeyRef:
                  key: DATA_API_ORIGIN
                  name: mssecrets
          image: gfwdockerhub/subscriptions
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 3600
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          name: subscriptions
          ports:
            - containerPort: 3600
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 3600
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
