apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
    app: gfw
  name: {name}
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "3600"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://{name}.default.svc.cluster.local:3600
          - name: MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: SUBSCRIPTIONS_MONGO_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: STATS_RECIPIENTS
            value: sergio.gordillo@vizzuality.com,abarrett@wri.org,charlie.hofmann@wri.org,mweisse@wri.org,raul.requero@vizzuality.com
          - name: FLAGSHIP_URL
            value: http://www.globalforestwatch.org
          - name: RW_FLAGSHIP_URL
            value: http://resourcewatch.org
          - name: API_GATEWAY_EXTERNAL_URL
            value: http://production-api.globalforestwatch.org
          - name: API_URL
            value: http://production-api.globalforestwatch.org
          - name: CARTODB_USER
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CARTODB_USER
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: SUBSCRIPTIONS_AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: SUBSCRIPTIONS_AWS_SECRET_ACCESS_KEY
          - name: API_GATEWAY_QUEUE_PROVIDER
            value: redis
          - name: API_GATEWAY_QUEUE_NAME
            value: mail_prod
          - name: API_GATEWAY_QUEUE_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI
          - name: REDIS_PORT_6379_TCP_ADDR
            value: localhost
          - name: REDIS_PORT_6379_TCP_PORT
            value: "6379"

        ports:
          - containerPort: 3600

      - name: redis
        image: redis
        ports:
         - containerPort: 6379
        resources:
         requests:
           memory: "0Mi"
           cpu: "0m"

      restartPolicy: Always
