apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gfw
  labels:
    name: subscriptions
    app: gfw
  name: subscriptions
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: subscriptions
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
      - name: subscriptions
        image: vizzuality/subscriptions
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "3600"
          - name: LOGGER_LEVEL
            value: "info"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://subscriptions.gfw.svc.cluster.local:3600
          - name: MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: SUBSCRIPTIONS_MONGO_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: STATS_RECIPIENTS
            value: abarrett@wri.org,charlie.hofmann@wri.org,mweisse@wri.org
          - name: FLAGSHIP_URL
            value: http://www.globalforestwatch.org
          - name: RW_FLAGSHIP_URL_PREPRODUCTION
            value: http://preproduction.resourcewatch.org
          - name: RW_FLAGSHIP_URL_PRODUCTION
            value: http://resourcewatch.org
          - name: RW_FLAGSHIP_URL_STAGING
            value: http://staging.resourcewatch.org
          - name: API_GATEWAY_EXTERNAL_URL
            value: http://production-api.globalforestwatch.org
          - name: API_URL
            value: http://production-api.globalforestwatch.org
          - name: CARTODB_USER
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CARTODB_USER
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: SUBSCRIPTIONS_AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: SUBSCRIPTIONS_AWS_SECRET_ACCESS_KEY
          - name: API_GATEWAY_QUEUE_PROVIDER
            value: redis
          - name: API_GATEWAY_QUEUE_NAME
            value: mail_prod
          - name: REDIS_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI
          - name: REDIS_PORT_6379_TCP_ADDR
            value: localhost
          - name: REDIS_PORT_6379_TCP_PORT
            value: "6379"

        ports:
          - containerPort: 3600
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 3600
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 3600
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15

      restartPolicy: Always
